### ISSUE TITLE
Readme has to contain only description of project

### ISSUE THREAD

**Issue by vkuchyn** [JuniorsJava/GSR#19]
Main page of project has to describe project at all, some general steps how to setup,build, run etc. Maybe, some samples of how to bootstrap. #18 information about Google oAuth was moved to wiki, so let's leave link to wiki and remove duplicates. Follow DRY principle everywhere!

**Comment by vkuchyn** [comment]
@sLisnychyi This issue for you

**Comment by sLisnychyi** [comment]
@vkuchyn 
updated main page in wiki and project. If you can add smth. please do
