### ISSUE TITLE
DAO: Create column if user id not found

### ISSUE THREAD

**Issue by vkuchyn** [JuniorsJava/GSR#7]
Якщо для користувача не знайдено колонку - просто додати її

**Comment by sLisnychyi** [comment]
i need some code review session for this

**Comment by sLisnychyi** [comment]
+ still can't assign task on myself

**Comment by vkuchyn** [comment]
> i need some code review session for this
@sLisnychyi  What kind of code review you need for this task?

**Comment by vkuchyn** [comment]
Let then assign tasks on you

**Comment by sLisnychyi** [comment]
@vkuchyn pls review
